### ISSUE TITLE
[Feature request] Support for audio recordings of core plugin ?

### ISSUE THREAD

**Issue by Elaws** [RainCat1998/obsidian-custom-attachment-location#13]
Hello,

I noticed Custom Attachment Location does not work for files from the audio recorder (Obsidian core plugin) : is this the expected behavior ? Is there any plan to support it ?

Thanks !

**Comment by RainCat1998** [comment]
I will consider it.

**Comment by pitibalrog** [comment]
It works for me using the panel button or Ctrl + P (Audio recorder : Start/Stop recording audio)

The webm file is in the good folder

Obsidian : v0.14.6
Windows 11
Custom Attachment Location : v0.0.7
Attachment location : `./${filename}.assets`

**Comment by pitibalrog** [comment]
I just make some more test and I finaly have your problem too.

It only occurs when I do a recording on a note without attachment.

So after searching to understand I think that the problem is that before adding an attachment, the default attachment path is used and it is modified only after having added an attachment file.

I found a contribution to the code which can help by updating this path at the opening of the file. Here is the code https://github.com/RainCat1998/obsidian-custom-attachment-location/pull/23

I'm new to github so sorry if I'm wrong.
