### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by psycho-baller** [RainCat1998/obsidian-custom-attachment-location#3]
So im trying to have a specified folder for all my audio recordings, I thought your plugin would do the job but it doesn't seem like it. I am interested in making my own plugin that does that if it's possible but thought that maybe u can easily implement it to your plugin instead of me making my own one. If u don't wanna make it plz lmk if that is actually doable, i havent made any plugins before and still a beginner in JS

**Comment by RainCat1998** [comment]
Audio recorder is a official core plugin which saves your audio records in attachment folder.(Files & Links -> Default location for new attachments"). 
Since the plugin is not open source and there is no API for plugin developer to specify folder only for audio recordings, it is not doable to make such plugin.(Maybe you can do some hacking tricks but I'm not sure).
**Here is a work around.** If you use my plugin and drag a file before saving your records, it will change "attachment folder setting" and the audio records will be saved into the folder specified in my plugin setting.

**Comment by psycho-baller** [comment]
Hey thank's for the response, I decided to just use my built in voice recorder app and make its path to a folder inside my vault, u can close the issue. Have a good life :)
