### ISSUE TITLE
Relative path contains ".." not work

### ISSUE THREAD

**Issue by whatsrtos** [RainCat1998/obsidian-custom-attachment-location#46]
Path like this: `./../_images` not work

**Comment by SuperTempAccount** [comment]
Not sure if this is related:

Using `.image` as the folder name creates the folder but does not create the attachments.
The reason I want to use an unnamed folder is so that it doesn't show in the obsidian file explorer.

![image](https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/83566267/6644f49a-ece2-4ca6-9ab6-133ed42f06ff)


![image](https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/83566267/e55134a3-7834-40b0-8d11-9f63d482f5a0)

**Comment by RainCat1998** [comment]
".." is not supported.
